### ISSUE TITLE
Only show 2nd SIM card indicator if there is a SIM card present

### ISSUE THREAD

**Issue by Flohack74** [ubports/indicator-network#1]
_From @Flohack74 on July 28, 2017 15:10_

The second empty SIM card symbol shows up on all phones with 2 SIM slots. This wasnt the original behaviour, but Canonical decided to always show this indicator later on.

I vote for not displaying any empty SIM card symbol IF the phone has more than 1 SIM slot. Advantage: Cleaner top bar, many users never use 2 SIM cards.
Disadvantage: If a SIM card fails, there will be no symbol for it but just the indicator disappears. But to me "no indicator" has the same level of information than "empty slot indicator".

Maybe we even extend it to 1 slot phones also. "empty slot indicator" has really not much information. If the users sees no indicator but a card is inside, smth is wrong with the hardware or the SIM card, and he will start looking for it.

_Copied from original issue: ubports/ubports-touch#185_

**Comment by Flohack74** [comment]
_From @mihaelmilea on July 28, 2017 17:43_

In my Meizu Pro 5 I have a micro SD card inserted in the first sim card slot. I would prefer instead of an empty sim card icon to have a symbol that shows an SD card is inserted. Maybe even active (more white in the icon) when read/write happens on the SD card. Or maybe even better to have in white the amount of used space on the SD card.

**Comment by Flohack74** [comment]
Good point but somehow unrelated: The SIM and SD card are handled by different services in the background. So one thing is how we handle SIM cards, the other one: We need a new concept for SD cards, yes. The current system setting does not much, and the icon is ugly. I can envision an "removable-media-indicator" that does exactly what you described.

**Comment by mardy** [comment]
I think we need to have a more transparent process for taking these decisions. Canonical added the indicator for a very good reason, now it feels like this was removed because of one person who uses only one SIM.

**Comment by NeoTheThird** [comment]
I think it was not a bad decision, but i see your point in general. What do you propose @mardy ?

**Comment by Flohack74** [comment]
I see no reason in that: Most of the people will in fact not use a second SIM, as the necessity for having 2 SIMs is really declining. Then, it was not my decision alone, as you can see I proposed it, I discussed it with a few people and we agreed.

What people are complaining about a lot is the filled space in the indicator bar. The bar itself as well as the dropdown menus should only contain *RELEVANT* information, and if there is no SIM in the slot, its not relevant ofr the user. This symbol gives him no actualy, changing information.

The edge case when a SIM gets broken and is no longer detected, or incorrectly inserted is covered by the user himself, not being able to use the SIM.

But what, I really mean it like this, what did they smoke to change it to that solution to always show it, even if it is forever empty?

**Comment by mardy** [comment]
The thing you call "edge case" is exactly the reason why this change initially happened, and it's far from being an edge case: most of the times when I change SIMs at least one of them is not detected (with nano SIMs and people cutting them manually this happens quite easily).
I understand that seeing an empty symbol is a cosmetic inconvenience to you, but for people that actually use two SIMs this informatio

**Comment by mardy** [comment]
Ops, the browser betrayed me :-)
...this information is essential.
So, while I agree that we might want to find a solution to the cosmetic issue, we shouldn't do that by introducing a serious issue to other users, no matter how few they are.

**Comment by Flohack74** [comment]
If the second SIM is empty/dead/unresponsive you will see that the 2nd indicator is missing, its the same kind of information than showing an empty indicator. You got 2 SIMs but only see one symbol? smth is wrong. You got only 1 sim and see one symbol. All ok. The information is in fact the missing 2nd symbol, and I use 2 sims myself, so I am pretty fine with that.

**Comment by mardy** [comment]
Sure, but
1) the presence of an error symbol is much more evident than his absence :-) I would not even notice that the indicator is missing among all the other ones.
2) users (especially first time users) won't even know that there has to be a symbol for each SIM: even if they notice that there's only one symbol, they might think that's fine, and that that symbol means that both SIMs are connected.

**Comment by mardy** [comment]
I've filed my suggestion as issue #3.
