### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by cibersheep** [ubports/indicator-network#12]
On Xenial dev 669, a string «Cellular Data» is not translated even if it's in the po
Needs to update translations?

![imatge](https://user-images.githubusercontent.com/6640041/47594414-8461b200-d97b-11e8-8eab-015e68077163.png)

**Comment by Flohack74** [comment]
We found the cause for that, its a wrong order in the CMakeLists.txt - it was using old Canonical translations always...

**Comment by cibersheep** [comment]
Nice. Thanks!

Let me know and I can check other places on the system that happens something similar

**Comment by Flohack74** [comment]
Yes, its all indicators basically. They were all wrong for what we do in our pipeline. Maybe Canonical did not care, as they delivered translations via the language packs in a different way.
However, there are major blockers in that all indicator pipelines are red, for various reasons. We need to fix this ASAP, we cannot update indicators for the next OTA!

**Comment by cibersheep** [comment]
Do you need me to do something?

**Comment by Flohack74** [comment]
Well idk who can fix this, there is a pbuilder warning inside, and it cannot install all required packages. Its a weirdness just for indicators it seems. But I will try to handle with the devel group...

**Comment by Danfro** [comment]
This seems to be quite old but still valid. :thinking: This string is still the same on current devel as today 2020-10-02.

**Comment by Flohack74** [comment]
Hmm no idea. I gave up on it, it resists translation, but nobody knows why...

**Comment by dobey** [comment]
Seems to have two problems causing this. Firstly, the translations path was not being set correctly, which my PR fixes. Secondly, it seems the indicator is loading the old translations from the Ubuntu langpacks, which does not have the string translated in at least some languages. I'm not sure why it is being forced to load those translations instead, or how we can solve this without probably breaking lots of other translations. This also probably causes some problems with other things as well.

**Comment by dobey** [comment]
OK, apparently I messed something up when testing this on Saturday and it actually is working correctly with my fix.

**Comment by TellingBerto** [comment]
Device: VollaPhone
Channel: rc
Build: 2020-W43

Result: Issue persist. 
Still "Cellular data" and not the expected translation in German.

**Comment by cibersheep** [comment]
It works on the latest dev update for Catalan :)

**Comment by TellingBerto** [comment]
Hi, this is sooo mean! I switched this mornig to RC for testing and now I´m
on an old release.
For me it is not working, but maybe with 2020-W44.

Am Di., 27. Okt. 2020 um 10:42 Uhr schrieb Joan CiberSheep <
notifications@github.com>:

**Comment by Flohack74** [comment]
Its fixed on latest devel 2020-10-27 for German as well. Guess your RC was not the current one?

**Comment by TellingBerto** [comment]
Hi Flo.
I updated yesterday before testing to RC 2020-w43. How can I update to a
newer one in RC? I have only one button to press. And this is the message I
see: "Die Software ist aktuell". R u also testing with VollaPhone? Cheers.

Am Di., 27. Okt. 2020 um 20:18 Uhr schrieb Florian Leeber <
notifications@github.com>:

**Comment by dobey** [comment]
> R u also testing with VollaPhone?

VollaPhone is not yet on same update schedule, and has some further modifications to indicator-network it seems, and has not yet pulled in this change. I guess this is why you aren't seeing it there.

**Comment by TellingBerto** [comment]
Hello Rodney,
ok. Fine for me. Will not wast further your nor mine time.
Br.

Am Mi., 28. Okt. 2020 um 17:43 Uhr schrieb Rodney <notifications@github.com

**Comment by FlavioMala** [comment]
OK, even on my BQ E5 the string has been translated as it was several months ago, but there is still some problem as you can see in the attached photo: the string "Connessione VPN 1" is in Italian (not English!), the rest in German as set.
It seems that, for some strange reason, when you change from one language to another something of the previous language remains...
![screenshot20201022_104402864](https://user-images.githubusercontent.com/50835740/98438822-1a914c80-20ed-11eb-894a-e46fd7e3fd91.png)

**Comment by Danfro** [comment]
Strange. @FlavioMala did you try clearing the cache for system settings with UT Tweak Tool?

**Comment by FlavioMala** [comment]
Just do it, but clearing system settings cache (+reboot) have no effect.
Other idea/test?

**Comment by Danfro** [comment]
It does look fine here. So unless someone else confirms your behaviour, I would guess it is more a software hiccup on your side.

Without any other ideas, how about switching your device to Italian and then back to German? Or try any other language.

**Comment by FlavioMala** [comment]
I switched to Spanish, but the string is always in Italian. I leave it for a few weeks / updates and see what happens, then I'll try another language (luckily I understand a dozen; 4/5 at a level enough to use the phone without... "launching the missiles") 
![screenshot20201107_185704816](https://user-images.githubusercontent.com/50835740/98448273-2e5ba380-212b-11eb-8c04-4b46794a469c.png)

**Comment by dobey** [comment]
> I switched to Spanish, but the string is always in Italian

Yes, this is not a translated string from the software. It is the name of your VPN connection. Presumably you created it when using Italian and used the generic default name. You will need to go to VPN settings and change the name, in order to have it be in a different language.

**Comment by FlavioMala** [comment]
(I didn't, or at least unintentional!)
Ahhhh... now I see. It is the "name" and not a "setting".

So, trying to create a new one, the name appears in the right language, as indicated. Thanks for the clarification.
Sorry!
(And... as "Bernd, das Brot" says... "Mist!")
![screenshot20201110_093510360](https://user-images.githubusercontent.com/50835740/98650803-af888580-2339-11eb-9721-bac424201f7e.png)

**Comment by dobey** [comment]
> (I didn't, or at least unintentional!)

OK, this is a user experience issue with the VPN config options in system settings. It seems that it doesn't provide a way to change the name of the connection. Can you please open a new and separate issue about not being able to adjust the name? Thanks.
