### ISSUE TITLE
indicator-network is failing to build in CI

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/indicator-network#21]
It appears there are issues with resolving dependencies for indicator-network in CI: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Findicator-network/detail/xenial/15/pipeline#step-47-log-972

Until this issue is resolved and indicator-network builds successfully, pull requests may not be merged.

**Comment by Flohack74** [comment]
We should fix this for OTA-12 because of translations...

**Comment by Flohack74** [comment]
Hmm is this still relevant?
