### ISSUE TITLE
Revert "fix" of issue #1

### ISSUE THREAD

**Issue by mardy** [ubports/indicator-network#3]
There were good reasons why Canonical decided to show the empty SIM indicator when a SIM slot is available but empty (or with a non-recognized card). We can only speculate about the real reasons (bug 1600712 cannot be found in launchpad, most likely because it was filed as a private bug), but I can find at least a couple of good ones:

1) Most often, when I switch SIMs at least one of them fails to be recognized: this issue is more frequent with nano SIMs, especially if they have been cut by hand. The user needs to be notified of the issue, and the assumption that the user will notice that there is only one SIM indicator is not granted: first of all, first time users will not know that the normal situation consists of two different SIMs; but in any case, even experienced users might not notice that an icon is not there, while the empty icon is clearly visible instead.

2) UI consistency: indicators work like this:
   a. if something is disabled, don't show it in the indicator
   b. if something is enabled but not working, show an empty indicator
   c. if something is enabled and active, show an active indicator
(Compare with WIFI) Our case is "b": the SIM slot is enabled, but not active, so the empty indicator should be shown.

If users find that the empty indicator is annoying (and I acknowledge that it can be, if a user has deliberately not put anything in a SIM slot), then I propose to add a switch next to the empty SIM (default to active), which if deactivated will hide the SIM from the top indicator. This setting could be replicated in the System Settings panel, under the "Connection type" group:
```
Connection Type:
  SIM 1:
    - No connection
    - 2G
    - 2G/3G
    ✓ 2G/3G/4G
  SIM 2:
    ✓ No connection
    - 2G
    - 2G/3G
    - 2G/3G/4G
```
In the above case, SIM 2 has been disabled, so no indicator should be shown for it. I wonder if this could be useful even when a valid SIM is present, in the case the user doesn't want to use it. Maybe not to be disturbed, ot to save even more battery -- I think I've read a request like this in the mailing list, once.

But anyway, this should be the subject of another issue: what I propose right now is to revert the "fix", as that is a bad regression for people who switch SIMs often or have a SIM with contacts slightly damaged. The beautification can come later :-)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/3

Sorry for your inconvenience.
