### ISSUE TITLE
mobile data not connected after flight mode

### ISSUE THREAD

**Issue by Danfro** [ubports/indicator-network#71]
Xperia X, devel, dual sim

To reproduce:
- turn on mobile data
- turn on flight mode
- leave the device in flight mode for some time (not just on/off, at least several minutes)
- turn off flight mode

Expected:
- mobile data is turned on again
- indicator does show the "L" for LTE
- dropdown indicator shows flight mode button off and mobile data button on

Actual behaviour:
- mobile data is still off = not working, no network connection there
- indicator does show empty wifi icon ("wifi-none")
- dropdown indicator shows flight mode button off and mobile data button on
- next to the provider, the "L" symbol is shown
I need to turn mobile data off via the button in the dropdown indicator and on again. Then mobile data connection is established.

Reproducable: always

I also did wait a while. But even after like half an hour nothing changes. I discovered this in august. So nothing brand new. But still the case, just tested right now.

![screenshot20210830_204112057](https://user-images.githubusercontent.com/37637312/132999146-6e0f0b48-2e9d-4caf-8ce1-536d689332d3.png)

**Comment by Danfro** [comment]
I had one confirmation in our German group by another user.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-indicator-network/-/issues/71

Sorry for your inconvenience.
